# Executes a request to the default http trigger of Azure function (includes orchestration logic)
POST http://localhost:7071/api/ask HTTP/1.1
content-type: application/json

{
    "prompt": "Where is the event happening?"
}

###
# Execute a sample 'ask' to the Kernel Memory service
POST https://km-service-e8a8fe.happypebble-4041b049.eastus.azurecontainerapps.io/ask HTTP/1.1
content-type: application/json

{
    "index": "default",
    "question": "Is OpenAI one of my talking points?",
    "minRelevance": 0.8

}

###
# Executes a sample 'search' to the Kernel Memory service
POST https://km-service-e8a8fe.happypebble-4041b049.eastus.azurecontainerapps.io/search HTTP/1.1
content-type: application/json

{
  "index": "default",
  "query": "OpenAI",
  "top": 1
}

###
# Uploads a file directly to the Kernel Memory service
POST https://km-service-e8a8fe.happypebble-4041b049.eastus.azurecontainerapps.io/upload HTTP/1.1
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

