@azfuncurl = http://localhost:7071
@kmserviceurl = http://localhost:9001

# Executes a request to the default http trigger of Azure function (includes orchestration logic)
POST {{azfuncurl}}/api/ask HTTP/1.1
content-type: application/json

{
    "prompt": "How do I setup an RRU?",
    "sessionId": "6"
}

###
POST {{azfuncurl}}/api/ask HTTP/1.1
content-type: application/json

{
    "prompt": "Which step talked about necessary tools and equipment?",
    "sessionId": "6"
}
###

#Delete a document from the Kernel Memory service using the Azure function
DELETE {{azfuncurl}}/api/documents HTTP/1.1
Accept: application/json

{
    "index": "default",
    "documentId": "PowerPlatDoc"
}

###
# Execute a sample 'ask' to the Kernel Memory service
POST {{kmserviceurl}}/ask HTTP/1.1
content-type: application/json
{
    "index": "default",
    "question": "Can I use the Icons for commercial products?"

}

###
# Executes a sample 'search' to the Kernel Memory service
POST {{kmserviceurl}}/search HTTP/1.1
content-type: application/json

{
  "index": "default",
  "query": "Orion Spacecraft",
  "limit": 1,
  "minRelevance": 0.5
}

###
# Uploads a file directly to the Kernel Memory service
POST {{kmserviceurl}}/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file1"; filename="CELA_Licenses_Public_Use_Icons.pdf"

Content-Type: application/pdf

(data)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="index"

default
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="documentId"

PowerPlatDoc
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# Delete a document from the Kernel Memory service
POST {{kmserviceurl}}/delete HTTP/1.1
content-type: application/json

{
    "index": "default",
    "documentId": "SKTEST"
}
